### ISSUE TITLE
Add user API call

### ISSUE THREAD

**Issue by FredericPasseron** [HewlettPackard/pyhpecfm#18]
Hi

Would it be possible to add the User api call in the python library to allow addition of multiple users in a automated fashion ?

**Comment by netmanchris** [comment]
Hi @FredericPasseron 

Happy to add this. Let me look at the API and then I'll come back with a couple of questions regarding how you want to use this.

**Comment by netmanchris** [comment]
Fixed in https://github.com/HewlettPackard/pyhpecfm/pull/22
