### ISSUE TITLE
v1/path 

### ISSUE THREAD

**Issue by Edrusb** [HewlettPackard/pyhpecfm#20]
Hi, 

it seems that the way to use the class CFMClient when it comes to operate on one of its instance by mean of get/patch/post/put methods is to prefix the path found in the API explorer by "v1/"

For example, from the explorer, one can read "GET  /vpcs    Get an array of VPC objects" but one has to use cfm.get("v1/vpcs") where cfm is an object of class CFMClient instead of cfm.get("/vpcs").

My 2 cents suggestion: 
- add an additional argument to the constructor of class CFMClient that is set have "v1" as default value and store this one in a new field of the object, we will call "version". The constructor thus be used the same as of today.

- let user use the same path as provided by the explorer, like "/vpcs" as path argument of methods get/post/patch/put/delete....
- modify the get/post/patch/put/delete/... methods this way:
- If the "version" field of the object is something else than an empty string (like "v1") prepend to the path provided as argument of the method as first instruction, the rest of the code does not change
- if the "version" field is empty, use the given path as is, so user can still provide "v1/vpcs" as argument if providing an empty string at object construction time to this new "version" field. 

my 2 cents.

I would have done a pull request for that but now that I know there is a different process I have openned an issue :-)

**Comment by netmanchris** [comment]
the class object isn't intended to be used directly in this way, but rather consumed by individual tested functions written into other modules of this library. 

There was a design decision to explicitly set the *v1* in the path of individual functions. The CFM is moving towards versioning and this design decision will allow the modification of individual functions in the future to use specific versions appropriate to the CFM instance they are connecting to. 

@bri365 @xod442 Do you see any reason in changing this behavior today? I don't think modifying the client portion to allow for direct access like this makes sense, but wiling to listen to other arguments.

**Comment by Edrusb** [comment]
So I maybe completely offbeat: but which "tested function" should I use to be able to dynamically add a vpc and place some SVI into it, in order to address the need of a multi-tenant application deployment done from a python environment? I have been doing that with Nutanix guys with from their Calm tool interacting with the CFM using the REST API, but how to do the same from Python??? I'm lost.

**Comment by netmanchris** [comment]
@Edrusb If I understand your request - Best way would be to open an issue for this use-case. Then we need to identify the specific API calls required to implement the use case and implement them with the appropriate tests for each function. Does that make sense?  If you know what APIs are being used by the Calm tool and the order of the calls, it should be pretty straight forward to implement that it python.

**Comment by Edrusb** [comment]
Hi @netmanchris, 
so the python binding is not "ready for use"?... Which is equivalent for many persons as "not possible to use" because you have to specify your need, advocate for your it, have it accepted, then wait for a new software abstraction to be developed for this particular use case and finally be able to go forward to your initial need.

Maybe a compromise would be better: having two levels of abstraction?
- a 1 to 1 low level same as what the API swagger proposes from CFM (by mean of a CFMClient equivalent class for example): I can propose a inherited class from CFMClient do do that if you want (no need to change the existing class)
- a higher abstracted level as what you request, I can detail the need also but it was more to play with the binding and do demo of what can be done than a real customer user case (so developing for that is maybe costly)

What do you think?
